// website/src/ui/AuthorPresentation/AuthorPresentation.svelte
<script lang="ts">
  import type { SupportedLanguages } from '@/infrastructure/config/types/language';

  import { getIntl } from '@/infrastructure/i18n/getServerSideLocales.server';
  import { getSocial } from '@/infrastructure/utils/seo';

  import DevToIcon from '@/ui/Icons/DevTo.svelte';

  import IconWrapper from '../../pages/[lang]/_ui/IconWrapper.svelte';
  import { GithubIcon, LinkedinIcon } from 'lucide-svelte';
  import type { QuerySiteDataReturnType } from '@/infrastructure/api/modules/siteData';

  export let lang: SupportedLanguages;
  export let siteData: QuerySiteDataReturnType;

  const defaultSeo = siteData.defaultSeo[lang];

  const intl = getIntl(lang);

  const github = getSocial(`github`, siteData);
  const twitter = getSocial(`twitter`, siteData);
  const linkedIn = getSocial(`linkedin`, siteData);
  const devTo = getSocial(`dev.to`, siteData);
</script>

<header
  class="flex flex-col-reverse justify-between md:flex-row mb-7 col-span-full"
>
  <aside class="flex flex-col w-full md:max-w-[75%] mt-4 md:mt-0">
    <h1
      class="font-sans text-2xl font-black md:text-3xl xl:text-4xl"
      data-testid="author__name"
    >
      {siteData.personalInformation.fullName}
    </h1>
    <p
      class="text-md md:text-md xl:text-lg mt-2.5"
      data-testid="author__description"
    >
      {defaultSeo?.description}
    </p>
    <section
      class="flex items-center flex-1 pt-5 space-x-4 dark:opacity-90 text-secondary"
    >
      <IconWrapper
        href={devTo.url}
        data-testid="author__linkedInUrl"
        title={intl.formatMessage({
          id: `authorPresentation.devToLinkTitle`,
        })}
      >
        <DevToIcon size={32} stroke="1.5" />
      </IconWrapper>
      <IconWrapper
        href={github.url}
        data-testid="author__githubUrl"
        title={intl.formatMessage({
          id: `authorPresentation.githubLinkTitle`,
        })}
      >
        <GithubIcon size={32} stroke="1.5" />
      </IconWrapper>
      <IconWrapper
        href={linkedIn.url}
        data-testid="author__linkedInUrl"
        title={intl.formatMessage({
          id: `authorPresentation.linkedInLinkTitle`,
        })}
      >
        <LinkedinIcon size={32} stroke="1.5" />
      </IconWrapper>
    </section>
  </aside>
  <figure class="relative w-20 h-20 rounded md:w-32 md:h-32">
    <slot name="img" />
  </figure>
</header>

// apps/website/src/screens/Home/components/AuthorPresentation/AuthorPresentation.tsx
import { GithubIcon, LinkedInIcon, TwitterIcon } from '@components/Icons';
import { useLocalization } from '@hooks/useLocalization';
import { getSocial } from '@utils/seo';
import Image from 'next/image';
import React from 'react';
import { defineMessage } from 'react-intl';
import siteData from 'site-data';
import tw from 'twin.macro';

const message = defineMessage({ id: 'authorPresentation.profileImageAlt' });

const styles = {
  header: tw`flex flex-col-reverse justify-between md:flex-row mb-7 col-span-full`,
  figure: tw`relative w-20 md:w-32 h-20 md:h-32 rounded`,
  image: tw`rounded-full object-cover`,
  content: {
    wrapper: tw`flex flex-col w-full md:max-width[75%] mt-4 md:mt-0`,
    title: tw`font-sans font-black text-2xl md:text-3xl xl:text-4xl`,
    description: tw`text-md md:text-md xl:text-lg mt-2.5`,
    icons: {
      wrapper: tw`flex items-center pt-5 flex-1 text-black opacity-60 dark:text-white dark:opacity-90 space-x-4`,
      icon: tw`w-6 lg:w-8`,
    },
  },
};

export const AuthorPresentation = () => {
  const { locale, formatMessage } = useLocalization();
  const defaultSeo = siteData.defaultSeo[locale];
  const github = getSocial('github');
  const twitter = getSocial('twitter');
  const linkedIn = getSocial('linkedin');

  return (
    <header css={styles.header}>
      <aside css={styles.content.wrapper}>
        <h1 css={styles.content.title} data-testid="author__name">
          {siteData.personalInformation.full_name}
        </h1>
        <p css={styles.content.description} data-testid="author__description">
          {defaultSeo?.description}
        </p>
        <section css={styles.content.icons.wrapper}>
          <a href={github.url} data-testid="author__githubUrl">
            <GithubIcon css={styles.content.icons.icon} />
          </a>
          <a href={twitter.url} data-testid="author__twitterUrl">
            <TwitterIcon css={styles.content.icons.icon} />
          </a>
          <a href={linkedIn.url} data-testid="author__linkedInUrl">
            <LinkedInIcon css={styles.content.icons.icon} />
          </a>
        </section>
      </aside>
      <figure css={styles.figure}>
        <Image
          css={styles.image}
          src={siteData.personalInformation.profile_pic.url}
          layout="fill"
          alt={formatMessage(message)}
          loading="eager"
        />
      </figure>
    </header>
  );
};
