// apps/website-astro/src/ui/MenuBarButton.tsx
import classNames from 'classnames';
import { type ComponentPropsWithRef, forwardRef } from 'react';

export const MenuButton = forwardRef<
  HTMLButtonElement,
  ComponentPropsWithRef<`button`>
>(function MenuButton({ className, ...props }, ref) {
  return (
    <button
      ref={ref}
      className={classNames(`flex p-2 place-content-center`, className)}
      {...props}
    />
  );
});

// apps/website/src/ui/MenuBar/MenuBarButton.svelte
<script lang="ts">
  import { mergeClasses } from '@/infrastructure/utils/misc';

  let className = '';

  export { className as class };
</script>

<button
  on:click
  on:keydown
  on:keyup
  {...$$restProps}
  class={mergeClasses(`flex p-2 place-content-center`, className)}
>
  <slot />
</button>
