// apps/website/src/components/MenuBar/MenuBar.tsx
import { CloseIcon, MenuIcon } from '@components/Icons';
import { Logo } from '@components/Logo';
import { SideMenu } from '@components/SideMenu';
import { useApp } from '@hooks/useApp';
import { useLocalization } from '@hooks/useLocalization';
import classNames from 'classnames';
import Link from 'next/link';
import { FC } from 'react';
import { LanguageSwitch } from './components/LanguageSwitch';
import { ThemeSwitch } from './components/ThemeSwitch';

export const MenuBar: FC = () => {
  const { sideMenu } = useApp();
  const { locale } = useLocalization();

  const Icon = sideMenu.isClosed ? MenuIcon : CloseIcon;

  return (
    <>
      <div
        className={classNames([
          'inset-x-0',
          'h-16',
          'z-40',
          'shadow',
          'bg-white dark:bg-blue-800',
          'transition-theme duration-200 ease',
          'mb-8 md:mb-12',
          !sideMenu.isClosed && 'sticky',
        ])}
      >
        <nav className={classNames(['items-center h-full', 'grid-container'])}>
          <section data-testid="menu-bar__logo" className="col-span-2">
            <Link href="/" locale={locale}>
              <a>
                <Logo />
              </a>
            </Link>
          </section>
          <section className="flex justify-end space-x-3 col-span-2 md:col-end-9 lg:col-end-13">
            <ThemeSwitch />
            <LanguageSwitch />
            <button
              className={menuButtonClasses}
              onClick={sideMenu.toggle}
              data-testid="side-menu-button"
            >
              <Icon className="w-6" />
            </button>
          </section>
        </nav>
      </div>
      <SideMenu />
    </>
  );
};

export const menuButtonClasses = 'p-2 flex place-content-center';

// apps/website-svelte/src/components/MenuBar.svelte
<script>
  import SiteLogo from './SiteLogo.svelte';
  import ThemeHandler from '@components/ThemeHandler.svelte';
  import SideMenuButton from '@components/SideMenuButton.svelte';
  import SideMenu from '@components/SideMenu.svelte';
</script>

<div
  class="inset-x-0 relative h-16 z-40 shadow bg-white dark:bg-blue-800 transition-theme duration-200 ease mb-8 md:mb-12"
>
  <nav class="items-center h-full grid-container">
    <a class="col-span-2" href="/">
      <SiteLogo />
    </a>
    <section
      class="flex justify-end space-x-3 col-span-2 md:col-end-9 lg:col-end-13"
    >
      <ThemeHandler />
      <SideMenuButton />
    </section>
  </nav>
</div>
<SideMenu />
