// apps/website/src/components/PostBasic/PostBasic.tsx
import styled from '@emotion/styled';
import classNames from 'classnames';
import Link from 'next/link';
import { FormattedDate } from 'react-intl';

import { Tag, Tags } from '~/components/Tags';
import { getTagUrl } from '~/utils/url';

const Wrapper = styled.section``;

export const PostBasic = ({
  title,
  subtitle,
  url,
  _type,
  publishedAt,
  tags,
  titleClassName,
  as = 'section',
  className,
}: PostBasicProps) => {
  return (
    <Wrapper as={as} className={className}>
      <Link href={url} className="relative inline-block cursor-pointer">
        <h3 className={classNames(['font-extrabold', titleClassName])}>
          {title}
        </h3>
      </Link>

      <div className="flex space-x-4 mb-2.5">
        <span className="block font-sans text-md">
          <time dateTime={publishedAt}>
            <FormattedDate
              value={publishedAt}
              year="numeric"
              month="short"
              day="2-digit"
            />
          </time>
        </span>
        {_type ? (
          <span
            className={classNames(
              {
                'bg-indigo-600': _type === 'post',
                'bg-yellow-600': _type === 'til',
              },
              'px-2 rounded-sm min-w-[40px] text-center font-bold text-gray-50 uppercase',
            )}
          >
            {_type}
          </span>
        ) : null}
      </div>
      {subtitle && (
        <p className="text-lg lg:text-md text-primary dark:text-gray-200 text-opacity-80 dark:text-opacity-100">
          {subtitle}
        </p>
      )}
      {tags ? (
        <Tags className="mt-4">
          {tags.map(({ name, slug, _id }) => (
            <Tag key={_id}>
              <Link href={getTagUrl(slug)} className="underline cursor-pointer">
                #{name}
              </Link>
            </Tag>
          ))}
        </Tags>
      ) : null}
    </Wrapper>
  );
};

export interface PostBasicProps {
  title: string;
  subtitle?: string;
  url: string;
  _type?: 'post' | 'til';
  className?: string;
  as?: React.ElementType;
  publishedAt: string;
  titleClassName?: string;
  tags: {
    name: string;
    slug: string;
    _id: string;
  }[];
}

// apps/website-svelte/src/components/PostBasic.svelte
<script lang="ts">
  import Tag from '@components/Tag.svelte';
  import Tags from '@components/Tags.svelte';
  import classNames from 'classnames';

  import { getTagUrl } from '../utils/url';
  interface PostBasicProps {
    title: string;
    subtitle?: string;
    url: string;
    type?: 'post' | 'til';
    publishedAt: string;

    tags: {
      name: string;
      slug: string;
      id: string;
    }[];
  }

  export let post: PostBasicProps;
  export let titleClassName: string = '';
  export let className: string = '';
</script>

<section class={classNames('shadow bg-color-secondary', className)}>
  <a class="relative inline-block cursor-pointer" href={post.url}>
    <h3 class={classNames('font-extrabold', titleClassName)}>{post.title}</h3>
  </a>

  <div class="flex space-x-4 mb-2.5">
    <span class="block text-md font-sans">
      <time dateTime={post.publishedAt} class="publish-date">
        {post.publishedAt}
      </time>
    </span>
    {#if post.type}
      <span
        class={classNames([
          'px-2 rounded-sm min-width[40px] text-center font-bold text-gray-50 uppercase',
          post.type === 'post' ? 'bg-indigo-600' : 'bg-yellow-600',
        ])}>{post.type}</span
      >
    {/if}
  </div>

  {#if post.subtitle}
    <p
      class="text-lg lg:text-md text-primary dark:text-gray-200 text-opacity-80 dark:text-opacity-100"
    >
      {post.subtitle}
    </p>
  {/if}

  {#if post.tags}
    <Tags className="mt-4">
      {#each post.tags as { name, slug }}
        <Tag>
          <a href={getTagUrl(slug)} class="tag-link">#{name}</a>
        </Tag>
      {/each}
    </Tags>
  {/if}
</section>
