// apps/website/src/pages/cv.tsx
import { ExternalLinkIcon } from '@components/Icons';
import classNames from 'classnames';
import { NextSeo } from 'next-seo';
import Image from 'next/image';
import React from 'react';
import { FormattedMessage } from 'react-intl';

const CurriculumPage = () => {
  return (
    <>
      <NextSeo
        title="Curriculum"
        description="Raul Melo is a Software Developer focused on client-side. Have over 5 years of experience building websites and applications. Check his CV for more info."
      />

      <header
        className={classNames(['leading-normal col-span-full lg:col-span-8'])}
      >
        <h1
          className={classNames([
            'text-2xl md:text-3xl lg:text-4xl',
            'font-black',
            'mb-4 md:mb-6',
          ])}
        >
          <FormattedMessage id="sideMenu.cv" />
        </h1>
        <p className="mb-4 text-base md:text-md lg:text-lg">
          <FormattedMessage id="cv.description1" />
        </p>
        <p className="mb-4 text-base md:text-md lg:text-lg">
          <FormattedMessage id="cv.description2" />
        </p>
      </header>

      <aside
        className={classNames([
          'col-span-full lg:col-span-4',
          'w-full max-w-[250px] md:max-w-[380px]',
          'shadow-md',
          'bg-white',
          'relative',
          'grid place-items-center',
          'mx-auto',
        ])}
      >
        <figure className={classNames('relative', 'h-full w-full')}>
          <Image
            src="https://res.cloudinary.com/duzei21zt/image/upload/v1617789904/site/cv_cover_dbad9dd714.png"
            layout="responsive"
            width={693}
            height={979}
            loading="eager"
          />
        </figure>
        <a
          href="https://docs.google.com/document/d/1xk0ChmPckqW85xtM1Hizx2tVbo2B61xjcpz-_dAH3f8"
          target="_blank"
          rel="noopener noreferrer"
          className={classNames([
            'bg-black dark:bg-blue-900',
            'rounded-md',
            'py-2 px-3 md:py-4 md:px-6',
            'text-base md:text-lg',
            'font-extrabold',
            'text-white',
            'absolute',
          ])}
        >
          <FormattedMessage
            id="cv.cta"
            values={{
              // eslint-disable-next-line react/display-name
              icon: () => (
                <ExternalLinkIcon className="w-4 inline-block mb-2 md:mb-4" />
              ),
            }}
          />
        </a>
      </aside>
    </>
  );
};

export default CurriculumPage;

// apps/website-svelte/src/routes/cv.svelte
<script>
  import ExternalLinkIcon from '@components/Icons/ExternalLinkIcon.svelte';
</script>

<header>
  <h1>Curriculum</h1>
  <p>
    To provide a better experience and ease the maintainability of a single
    source of true, I keep my CV in a public Google Docs file.
  </p>
  <p>
    From there, you'll be able to print or export in the extension you need.
  </p>
</header>

<aside class="image-container">
  <figure>
    <img
      src="https://res.cloudinary.com/duzei21zt/image/upload/v1617789904/site/cv_cover_dbad9dd714.png"
      alt="cv"
    />
  </figure>
  <a
    class="cta"
    href="https://docs.google.com/document/d/1xk0ChmPckqW85xtM1Hizx2tVbo2B61xjcpz-_dAH3f8"
    target="_blank"
    rel="noopener noreferrer"
  >
    Go to the document <span class="icon-wrapper"><ExternalLinkIcon /></span>
  </a>
</aside>

<style lang="postcss">
  header {
    @apply leading-normal col-span-full lg:col-span-8;
  }
  header h1 {
    @apply text-2xl md:text-3xl lg:text-4xl font-black mb-4 md:mb-6;
  }
  header p {
    @apply mb-4 text-base md:text-md lg:text-lg;
  }

  .image-container {
    @apply col-span-full lg:col-span-4;
    @apply w-full max-w-[250px] md:max-w-[380px];
    @apply shadow-md;
    @apply bg-white;
    @apply relative;
    @apply grid place-items-center;
    @apply mx-auto;
  }

  figure {
    @apply relative h-full w-full;
  }

  .cta {
    @apply bg-secondary transition-theme;
    @apply rounded-md;
    @apply py-2 px-3 md:py-4 md:px-6;
    @apply text-base md:text-lg;
    @apply font-extrabold;
    @apply text-white dark:text-black;
    @apply absolute;
  }
  .cta .icon-wrapper {
    @apply w-4 inline-block mb-2 md:mb-4;
  }
</style>
